title: Sentipedia
email: a.pei@lse.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Using Python and R to conduct emotional and sentiment analysis on the issue of Brexit.
base_url: "/sentipedia"
url: "https://andrewtpei.github.io/sentipedia/"

theme: minima
plugins: 
    - jekyll-feed