title: DS105L 
email: a.pei@lse.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  DS105L is a course on data science for the social sciences.
base_url: "/sentipedia"
url: "https://andrewtpei.github.io/sentipedia/"

theme: minima
plugins: 
    - jekyll-feed