```{r}
library(jsonlite);library(RedditExtractoR);library(tidyverse);library(purrr);library(tidytext); library(wordcloud2); library(textdata); library(syuzhet); library(lubridate); library(ggrepel); library(directlabels); library(ggthemes); library(sentimentr)
```

```{r}
#Naive Emotional Classification
filteredemotion1 <- filtered %>% sentimentr::get_sentences() %>% sentimentr::emotion()
```

```{r}
#Time Graph of Emotions
emotion2 <- filteredemotion1 %>% dplyr::filter(emotion_count > 0) %>% arrange(date) %>% #only keep instances where an emotion count was recorded for a comment
  group_by(url, emotion_type) %>% #group by url link (i.e each news article) and emotions 
  summarise(Emotion_Percentage = sum(emotion_count)) %>% 
  pivot_wider(names_from = emotion_type, values_from = Emotion_Percentage) %>% #gets data in desired format of where rows correspond to each post and columns are counts of each emotion. 
  mutate(across(everything(), ~ replace_na(., 0))) %>% data.frame() %>% #removes all NA values
  select(-anger_negated, -fear_negated, -anticipation_negated, -joy_negated, -trust_negated, -sadness_negated, -surprise_negated,
         -disgust_negated, -trust, -anticipation) %>% 
  mutate(rowSum = rowSums(select(.,-url))) %>% #obtains sum of each row excluding the url column
  mutate(Date = as.Date(Atop_Brexit_urls$date_utc)) %>%  mutate(Year = year(Date)) %>% #attaches date of the Brexit url and converts it to date format. the dates should correspond to the correct urls as both Atop_Brexit_url and filteredemotion1 have been arranged from earliest to latest date. 
  group_by(Year) %>% top_n(3, rowSum) %>% ungroup() %>% #take the top 3 values of each year
  arrange(Date) %>% 
  mutate(across(-c("Date","rowSum","url","Year"), ~ (./rowSum*100))) %>% #convert into percentages 
  pivot_longer(-c("Date","url", "Year", "rowSum"), names_to = "Emotions", values_to = "Emotion") 
head(emotion2)
summary(emotion2)
```

```{r}
plot2 <- ggplot(emotion2, aes(x = Date, y = Emotion, group = Emotions)) +
  geom_smooth(aes(color = Emotions), se = FALSE) + 
  labs(title = "Reddit Emotional Prevalence between 2016-2023", x = "Time", y = "Emotion Frequency Percentage (%)", subtitle = "Which emotions dominated Brexit-related reddit discussions over time?") + 
    theme_fivethirtyeight() + 
    theme(axis.title = element_text(), plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5)) +
    theme(text = element_text(family = "mono")) + 
  scale_x_date(date_labels = "%Y", date_breaks = "1 year") + 
   guides(color = guide_legend(nrow = 1))
plot2
```




