```{r}
library(RedditExtractoR);library(tidyverse);library(tidytext); library(wordcloud2); library(textdata); library(gridExtra); library(gridGraphics); library(ggplotify); library(plotly); library(ggwordcloud)
```

```{r}
reddit_Brexit <- read_csv("~/Downloads/sentipedia/Coding implementation/nltk/reddit_Brexit.csv")
```

```{r}
df_bigrams <- df_filtered %>%
  unnest_tokens(bigram, comment, token = "ngrams", n = 2) %>%
  filter(!is.na(bigram))
bigrams_separated <- df_bigrams %>% separate(bigram, c("word1", "word2"), sep = " ")
```

```{r}
#Cleaning to obtain mostly emotional words
custom_stopwords <- c("http", "amp", "https", "gt", "xit", "news", "wiki", "makes", "mail", "brexit")
bigrams_filtered <- bigrams_separated %>%
  filter(!word1 %in% stop_words$word & !word2 %in% stop_words$word) %>% #uses a stopword dataframe from the tidytext package
  filter(word1 %in% sentiments$word | word2 %in% sentiments$word) %>% 
  filter(!word1 %in% custom_stopwords & !word2 %in% custom_stopwords)

bigrams_united <- bigrams_filtered %>%
  unite(bigram, word1, word2, sep = " ")
```

```{r}
#Split bigrams by time period
n <- nrow(bigrams_united)
bigrams_separated1 <- bigrams_united[1:round(n/4), ]
bigrams_separated2 <- bigrams_united[(round(n/4) + 1):round(n/2), ]
bigrams_separated3 <- bigrams_united[(round(n/2) + 1):round(3*n/4), ]
bigrams_separated4 <- bigrams_united[(round(3*n/4) + 1):n, ]
```

```{r}
#Emotional bigram wordcloud over time: 
bicloud1 <- bigrams_separated1 %>% count(bigram, sort = T) %>% top_n(n = 50, wt = n); bicloud2<- bigrams_separated2 %>% count(bigram, sort = T) %>% top_n(n = 50, wt = n); bicloud3 <- bigrams_separated3 %>% count(bigram, sort = T) %>% top_n(n = 50, wt = n); bicloud4 <- bigrams_separated4 %>% count(bigram, sort = T) %>% top_n(n = 50, wt = n)
#Converting the 4 split bigrams into a wordcloudable format. 
#Convert into 4 word clouds covering different time periods
cloud1<- wordcloud2(bicloud1, shape = "circle", fontFamily = "mono"); cloud2<- wordcloud2(bicloud2, shape = "circle", fontFamily = "mono"); cloud3<- wordcloud2(bicloud3, shape = "circle", fontFamily = "mono"); cloud4 <- wordcloud2(bicloud4, shape = "circle", fontFamily = "mono") 

cloud1;cloud2;cloud3;cloud4
```
